#!/usr/bin/env python
""" Py3GuiTest.py --

 UI generated by GUI Builder Build 146 on 2016-08-21 19:39:37 from:
    /home/fschaitb/programming/python/Py3GuiTest.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from tkinter import *
from Py3GuiTest_ui import Py3GuiTest

# BEGIN USER CODE global

# END USER CODE global

class CustomPy3GuiTest(Py3GuiTest):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_1_command --
    #
    # Callback to handle _button_1 widget option -command
    def _button_1_command(self, *args):
        pass

    # _checkbutton_1_command --
    #
    # Callback to handle _checkbutton_1 widget option -command
    def _checkbutton_1_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomPy3GuiTest(root)
    root.title('Py3GuiTest')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
