""" Py3GuiTest_ui.py --

 UI generated by GUI Builder Build 146 on 2016-08-21 19:39:37 from:
    /home/fschaitb/programming/python/Py3GuiTest.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Py3GuiTest(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._button_1 = tkinter.Button(root,
            text = "Button1",
        )
        self._checkbutton_1 = tkinter.Checkbutton(root,
            takefocus = 0,
            text = "CHeckBox1",
        )

        # widget commands

        self._button_1.configure(
            command = self._button_1_command
        )
        self._checkbutton_1.configure(
            command = self._checkbutton_1_command
        )


        # Geometry Management
        self._button_1.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._checkbutton_1.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 160, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 261, pad = 0)


